In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import pickle
from tensorflow.keras.models import load_model

In [2]:
### Load the trained model
model=load_model('model.h5')

WARNING:tensorflow:From C:\Users\ASUS\Documents\AI ML Langchain\annclassification\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [33]:
with open('onehotencoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

In [34]:
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [35]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [36]:
list(label_encoder_geo.get_feature_names_out())

['Geography_France', 'Geography_Germany', 'Geography_Spain']

In [22]:
test_point=pd.DataFrame([input_data])

In [38]:
label_encoder_geo.transform(test_point[['Geography']]).toarray()

array([[1., 0., 0.]])

In [40]:
temp=pd.DataFrame(label_encoder_geo.transform(test_point[['Geography']]).toarray(),columns=list(label_encoder_geo.get_feature_names_out()))

In [45]:
test_point=pd.concat([test_point.drop('Geography',axis=1),temp],axis=1)

In [46]:
test_point

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [48]:
test_point['Gender']=label_encoder_gender.transform(test_point['Gender'])

In [49]:
test_point

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [50]:
scaler.transform(test_point)

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [58]:
geo=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_df=pd.DataFrame(geo,columns=label_encoder_geo.get_feature_names_out())

C:\Users\ASUS\Documents\AI ML Langchain\annclassification\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [59]:
geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [60]:
test_point

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [62]:
input_scaled=scaler.transform(test_point)

In [64]:
model.predict(input_scaled)

1/1 [==============================] - 0s 73ms/step

array([[0.04121317]], dtype=float32)

In [65]:
pred_prob=model.predict(input_scaled)

1/1 [==============================] - 0s 39ms/step

In [68]:
pred_prob=pred_prob[0][0]